# Generated by Django 4.1 on 2023-07-09 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Server01", "0002_alter_user_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.CharField(
                default="http://localhost:8000/static/img/avatar/defaultAvatar.jpg",
                max_length=64,
                verbose_name="头像",
            ),
        ),
    ]
