# Generated by Django 4.1 on 2023-07-09 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Server01", "0003_alter_user_avatar"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="email",
            field=models.CharField(
                default="123@123.com", max_length=32, verbose_name="邮箱"
            ),
        ),
    ]
