# Generated by Django 4.1 on 2023-07-09 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Server01", "0004_user_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="followed",
            field=models.ManyToManyField(
                blank=True, related_name="focusOn", to="Server01.user"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="following",
            field=models.ManyToManyField(
                blank=True, related_name="beFocusOn", to="Server01.user"
            ),
        ),
    ]
