# Generated by Django 4.1 on 2023-07-09 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Server01", "0005_user_followed_alter_user_following"),
    ]

    operations = [
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("imagePath", models.CharField(max_length=32, verbose_name="帖子图片")),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Server01.post"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="post",
            name="images",
            field=models.ManyToManyField(
                blank=True, related_name="imgs", to="Server01.image"
            ),
        ),
    ]
