# Generated by Django 4.1 on 2023-07-09 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Server01", "0007_alter_image_imagepath_alter_user_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="collected",
            field=models.ManyToManyField(
                blank=True, related_name="collectedPosts", to="Server01.post"
            ),
        ),
    ]
