# Generated by Django 4.1 on 2023-07-09 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Server01", "0008_alter_user_collected"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="favorites",
            field=models.ManyToManyField(
                blank=True, related_name="favoritePosts", to="Server01.post"
            ),
        ),
    ]
