# Generated by Django 4.1 on 2023-07-11 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Server01", "0010_remove_post_images_alter_image_post"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="followed",
        ),
    ]
