# Generated by Django 4.1 on 2023-07-27 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Server01", "0011_remove_user_followed"),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="height",
            field=models.IntegerField(default=0, verbose_name="图片高度"),
        ),
        migrations.AddField(
            model_name="image",
            name="width",
            field=models.IntegerField(default=0, verbose_name="图片宽度"),
        ),
    ]
